import { Course } from './types';

// Source: golfvedur.is (belgingur.is API) — 60 courses, coordinates verified
// Logos: rastimar.golf.is (Supabase CDN)
const LOGO = (file: string) =>
  `https://ivswzdjgcsociqyoomki.supabase.co/storage/v1/object/public/clubs//${file}`;

export const COURSES: Course[] = [

  // ── Capital Region ───────────────────────────────────────────────────
  {
    id: 'brautarholt',
    name: 'Brautarholt',
    shortName: 'Brautarholt',
    location: 'Reykjavík',
    region: 'Capital Region',
    lat: 64.2420939,
    lon: -21.8771,
    description: 'Golfklúbbur Brautarholts. One of Iceland\'s most storied clubs in the heart of the capital.',
    holes: 18,
    logoUrl: LOGO('gbr.png'),
  },
  {
    id: 'grafarholt',
    name: 'Grafarholtsvöllur',
    shortName: 'Grafarholt',
    location: 'Reykjavík',
    region: 'Capital Region',
    lat: 64.123503,
    lon: -21.76865,
    description: 'Golfklúbbur Reykjavíkur. Iceland\'s oldest and largest golf club, founded 1934.',
    holes: 18,
    logoUrl: LOGO('gr.svg'),
  },
  {
    id: 'korpulfstadir',
    name: 'Korpúlfstaðarvöllur',
    shortName: 'Korpúlfstaðir',
    location: 'Reykjavík',
    region: 'Capital Region',
    lat: 64.1534,
    lon: -21.7587,
    description: 'Golfklúbbur Reykjavíkur. Second course of the oldest club in Iceland, set in the Korpúlfsstaðir area.',
    holes: 18,
    logoUrl: LOGO('gr.svg'),
  },
  {
    id: 'hlidavollur',
    name: 'Hlíðavöllur / Bakkakotsvöllur',
    shortName: 'Hlíðavöllur',
    location: 'Mosfellsbær',
    region: 'Capital Region',
    lat: 64.17194,
    lon: -21.72719,
    description: 'Golfklúbbur Mosfellsbæjar. Sheltered valley course just outside the capital.',
    holes: 18,
    logoUrl: LOGO('gmos.png'),
  },
  {
    id: 'hvaleyrarvollur',
    name: 'Hvaleyrarvöllur',
    shortName: 'Keilir',
    location: 'Hafnarfjörður',
    region: 'Capital Region',
    lat: 64.058953,
    lon: -21.991956,
    description: 'Golfklúbburinn Keilir. Top-ranked Icelandic course on the dramatic Hvalseyrí peninsula.',
    holes: 18,
    logoUrl: LOGO('keilir.png'),
  },
  {
    id: 'alftanesvollur',
    name: 'Álftanesvöllur',
    shortName: 'Álftanes',
    location: 'Álftanes',
    region: 'Capital Region',
    lat: 64.1003,
    lon: -22.0295,
    description: 'Golfklúbbur Álftaness. Scenic coastal course on the Álftanes peninsula near the Presidential residence.',
    holes: 9,
    logoUrl: LOGO('galftanes.png'),
  },
  {
    id: 'leirdalur',
    name: 'Leirdalur',
    shortName: 'Leirdalur',
    location: 'Garðabær',
    region: 'Capital Region',
    lat: 64.08427,
    lon: -21.88276,
    description: 'Golfklúbbur Kópavogs og Garðabæjar. Well-appointed course in the capital suburbs.',
    holes: 18,
    logoUrl: LOGO('gkg.png'),
  },
  {
    id: 'nesvollur',
    name: 'Nesvöllur',
    shortName: 'Nesklúbburinn',
    location: 'Seltjarnarnes',
    region: 'Capital Region',
    lat: 64.152844,
    lon: -22.029347,
    description: 'Nesklúbburinn. Ocean-side course on the Seltjarnarnes peninsula with panoramic views.',
    holes: 18,
    logoUrl: LOGO('nesklubburinn.png'),
  },
  {
    id: 'setbergsvollur',
    name: 'Setbergsvöllur',
    shortName: 'Setberg',
    location: 'Hafnarfjörður',
    region: 'Capital Region',
    lat: 64.066753,
    lon: -21.923019,
    description: 'Golfklúbburinn Setberg. Welcoming 9-hole club in Hafnarfjörður.',
    holes: 9,
    logoUrl: LOGO('setberg.jpg'),
  },
  {
    id: 'urridavollur',
    name: 'Urriðavöllur',
    shortName: 'Oddur',
    location: 'Garðabær',
    region: 'Capital Region',
    lat: 64.05959,
    lon: -21.89612,
    description: 'Golfklúbburinn Oddur. Course set around the Urriðavatn lake in Garðabær.',
    holes: 18,
    logoUrl: LOGO('oddur.png'),
  },

  // ── Reykjanes ────────────────────────────────────────────────────────
  {
    id: 'holmsvollur',
    name: 'Hólmsvöllur',
    shortName: 'Hólmsvöllur',
    location: 'Reykjanesbær',
    region: 'Reykjanes',
    lat: 64.04211,
    lon: -22.59722,
    description: 'Golfklúbbur Suðurnesja. Full 18-hole course near Keflavík on the Reykjanes peninsula.',
    holes: 18,
    logoUrl: LOGO('gsudurnes.png'),
  },
  {
    id: 'husatoftavollur',
    name: 'Húsatóftavöllur',
    shortName: 'Húsatóftavöllur',
    location: 'Grindavík',
    region: 'Reykjanes',
    lat: 63.83264,
    lon: -22.5092,
    description: 'Golfklúbbur Grindavíkur. Course on the lava fields near the Blue Lagoon.',
    holes: 9,
    logoUrl: LOGO('grindavik.webp'),
  },
  {
    id: 'kalfatjarnarvollur',
    name: 'Kálfatjarnarvöllur',
    shortName: 'Kálfatjörn',
    location: 'Vogur',
    region: 'Reykjanes',
    lat: 64.0144,
    lon: -22.29115,
    description: 'Golfklúbbur Vatnsleysustrandar. Coastal course in the Vatnsleysuströnd area.',
    holes: 9,
    logoUrl: LOGO('vatnsleysustrond.jpg'),
  },
  {
    id: 'kirkjubolsvollur',
    name: 'Kirkjubólsvöllur',
    shortName: 'Kirkjuból',
    location: 'Sandgerði',
    region: 'Reykjanes',
    lat: 64.06574,
    lon: -22.69508,
    description: 'Golfklúbbur Sandgerðis. Course near the southwestern tip of the Reykjanes peninsula.',
    holes: 9,
    logoUrl: LOGO('sandgerdi.jpg'),
  },

  // ── South Iceland ────────────────────────────────────────────────────
  {
    id: 'gufudalsvollur',
    name: 'Gufudalsvöllur',
    shortName: 'Gufudalur',
    location: 'Hveragerði',
    region: 'South Iceland',
    lat: 64.01706,
    lon: -21.18556,
    description: 'Golfklúbbur Hveragerðis. Course in the geothermal town of Hveragerði.',
    holes: 9,
    logoUrl: LOGO('hveragerdi.jpg'),
  },
  {
    id: 'haukadalsvollur',
    name: 'Haukadalsvöllur',
    shortName: 'Geysir',
    location: 'Haukadalur',
    region: 'South Iceland',
    lat: 64.312951,
    lon: -20.277135,
    description: 'Golfklúbburinn Geysir. Course near the famous Geysir hot springs in Haukadalur.',
    holes: 9,
  },
  {
    id: 'kidjabergsvollur',
    name: 'Kiðjabergsvöllur',
    shortName: 'Kiðjaberg',
    location: 'Selfoss',
    region: 'South Iceland',
    lat: 64.00093,
    lon: -20.77878,
    description: 'Golfklúbbur Kiðjabergs. Rural course in the South Iceland lowlands.',
    holes: 9,
    logoUrl: LOGO('kidjaberg.png'),
  },
  {
    id: 'selsvollur',
    name: 'Selsvöllur',
    shortName: 'Flúðir',
    location: 'Flúðir',
    region: 'South Iceland',
    lat: 64.14112,
    lon: -20.35916,
    description: 'Golfklúbburinn Flúðir. Course in the geothermal village of Flúðir.',
    holes: 9,
    logoUrl: LOGO('fludir.png'),
  },
  {
    id: 'strandarvollur',
    name: 'Strandarvöllur',
    shortName: 'Hella',
    location: 'Hella',
    region: 'South Iceland',
    lat: 63.79915,
    lon: -20.30655,
    description: 'Golfklúbbur Hellu. Course on the South Iceland plains near Hella.',
    holes: 9,
    logoUrl: LOGO('hella.jpg'),
  },
  {
    id: 'svarfholsvollur',
    name: 'Svarfhólsvöllur',
    shortName: 'Selfoss',
    location: 'Selfoss',
    region: 'South Iceland',
    lat: 63.948,
    lon: -20.97853,
    description: 'Golfklúbbur Selfoss. The main 18-hole course serving the largest town in South Iceland.',
    holes: 18,
    logoUrl: LOGO('selfoss.png'),
  },
  {
    id: 'uthlidarvollur',
    name: 'Úthlíðarvöllur',
    shortName: 'Úthlíð',
    location: 'Bláskógarbyggð',
    region: 'South Iceland',
    lat: 64.2748,
    lon: -20.4364,
    description: 'Golfklúbburinn Úthlíð. Course in the Bláskógarbyggð highlands.',
    holes: 9,
    logoUrl: LOGO('uthlid.jpg'),
  },
  {
    id: 'vestmannaeyjar',
    name: 'Vestmannaeyjavöllur',
    shortName: 'Vestmannaeyjar',
    location: 'Vestmannaeyjar',
    region: 'South Iceland',
    lat: 63.43704,
    lon: -20.29779,
    description: 'Golfklúbbur Vestmannaeyja. Island course surrounded by dramatic volcanic scenery.',
    holes: 18,
    logoUrl: LOGO('vstmannaeyjar.jpg'),
  },
  {
    id: 'vik',
    name: 'Vík',
    shortName: 'Vík',
    location: 'Vík í Mýrdal',
    region: 'South Iceland',
    lat: 63.4198,
    lon: -18.9934,
    description: 'Golfklúbburinn Vík. Course near Iceland\'s southernmost point and famous black sand beaches.',
    holes: 9,
    logoUrl: LOGO('golfklubburinn-vik.jpg'),
  },
  {
    id: 'thorlaksvollur',
    name: 'Þorláksvöllur',
    shortName: 'Þorlákshöfn',
    location: 'Þorlákshöfn',
    region: 'South Iceland',
    lat: 63.87001,
    lon: -21.37457,
    description: 'Golfklúbbur Þorlákshafnar. Coastal course near the Vestmannaeyjar ferry terminal.',
    holes: 9,
    logoUrl: LOGO('thorlakshofn.jpg'),
  },
  {
    id: 'thverarvolur',
    name: 'Þverárvöllur',
    shortName: 'Hellishólar',
    location: 'Hvolsvöllur',
    region: 'South Iceland',
    lat: 63.7246,
    lon: -20.0398,
    description: 'Golfklúbburinn Þverá Hellishólum. Course near Hvolsvöllur under the shadow of Eyjafjallajökull.',
    holes: 9,
  },
  {
    id: 'ondverdanesvollur',
    name: 'Öndverðanesvöllur',
    shortName: 'Öndverðarnes',
    location: 'Selfoss',
    region: 'South Iceland',
    lat: 64.00953,
    lon: -20.92182,
    description: 'Golfklúbbur Öndverðarness. Rural course south of Selfoss.',
    holes: 9,
    logoUrl: LOGO('ondverdarness.jpg'),
  },

  // ── West Iceland ─────────────────────────────────────────────────────
  {
    id: 'dalbui',
    name: 'Dalbúi',
    shortName: 'Dalbúi',
    location: 'Borgarfjörður',
    region: 'West Iceland',
    lat: 64.24549,
    lon: -20.65962,
    description: 'Golfklúbburinn Dalbúi. Inland course in the Borgarfjörður region.',
    holes: 9,
    logoUrl: LOGO('dalbui.jpg'),
  },
  {
    id: 'frodarvollur',
    name: 'Fróðárvöllur',
    shortName: 'Fróðárdalur',
    location: 'Ólafsvík',
    region: 'West Iceland',
    lat: 64.8878,
    lon: -23.6094,
    description: 'Golfklúbburinn Jökull. Remote Snæfellsnes course near Ólafsvík with glacier views.',
    holes: 9,
    logoUrl: LOGO('jokull.jpg'),
  },
  {
    id: 'gardavollur-akranes',
    name: 'Garðavöllur',
    shortName: 'Leynir',
    location: 'Akranes',
    region: 'West Iceland',
    lat: 64.31895,
    lon: -22.03493,
    description: 'Golfklúbburinn Leynir. Well-regarded 18-hole course in the town of Akranes.',
    holes: 18,
    logoUrl: LOGO('leynir.jpg'),
  },
  {
    id: 'gardavollur-jokli',
    name: 'Garðavöllur undir Jökli',
    shortName: 'Staðarsveit',
    location: 'Snæfellsbær',
    region: 'West Iceland',
    lat: 64.8137,
    lon: -23.1391,
    description: 'Golfklúbbur Staðarsveitar. Course under the Snæfellsjökull glacier on the Snæfellsnes peninsula.',
    holes: 9,
    logoUrl: LOGO('stadarsveit.jpg'),
  },
  {
    id: 'glannavollur',
    name: 'Glannavöllur',
    shortName: 'Glanni',
    location: 'Borgarnes',
    region: 'West Iceland',
    lat: 64.76467,
    lon: -21.55107,
    description: 'Golfklúbburinn Glanni. Course near the Glanni waterfall in the Norðurá river valley.',
    holes: 9,
    logoUrl: LOGO('glanni.png'),
  },
  {
    id: 'grundarfjardarvollur',
    name: 'Grundarfjarðarvöllur',
    shortName: 'Grundarfjörður',
    location: 'Grundarfjörður',
    region: 'West Iceland',
    lat: 64.9746,
    lon: -23.2146,
    description: 'Golfklúbburinn Vestarr. Course in Grundarfjörður with views of the iconic Kirkjufell mountain.',
    holes: 9,
  },
  {
    id: 'hamarsvollur',
    name: 'Hamarsvöllur',
    shortName: 'Borgarnesi',
    location: 'Borgarnes',
    region: 'West Iceland',
    lat: 64.5903,
    lon: -21.87828,
    description: 'Golfklúbbur Borgarness. Course near the historic settlement-age town of Borgarnes.',
    holes: 9,
    logoUrl: LOGO('borgarnes.png'),
  },
  {
    id: 'husafellsvollur',
    name: 'Húsafellsvöllur',
    shortName: 'Húsafell',
    location: 'Húsafell',
    region: 'West Iceland',
    lat: 64.699133,
    lon: -20.871099,
    description: 'Golfklúbbur Húsafells. Course at the popular Húsafell highland resort in Borgarfjörður.',
    holes: 9,
  },
  {
    id: 'reykholtsdalsvollur',
    name: 'Reykholtsdalsvöllur',
    shortName: 'Reykholt',
    location: 'Reykholt',
    region: 'West Iceland',
    lat: 64.6629,
    lon: -21.33985,
    description: 'Golfklúbburinn Skrifla. Course in the Reykholtsdalur valley near historic Reykholt.',
    holes: 9,
  },
  {
    id: 'vikurvollur',
    name: 'Víkurvöllur',
    shortName: 'Mostri',
    location: 'Stykkishólmur',
    region: 'West Iceland',
    lat: 65.0698,
    lon: -22.7278,
    description: 'Golfklúbburinn Mostri. Course in the charming harbour town of Stykkishólmur.',
    holes: 9,
  },
  {
    id: 'bygdarholt-west',
    name: 'Byggðarholtsvöllur',
    shortName: 'Byggðarholt',
    location: 'Borgarbyggð',
    region: 'West Iceland',
    lat: 64.6466074,
    lon: -20.617447,
    description: 'Golfklúbbur Byggðarholts. Course in the rural Borgarbyggð municipality.',
    holes: 9,
  },

  // ── Westfjords ────────────────────────────────────────────────────────
  {
    id: 'litlueyrarvollur',
    name: 'Litlueyrarvöllur',
    shortName: 'Bíldudal',
    location: 'Bíldudal',
    region: 'Westfjords',
    lat: 65.67165,
    lon: -23.62,
    description: 'Golfklúbbur Bíldudals. Small course in the remote Westfjords village of Bíldudal.',
    holes: 9,
    logoUrl: LOGO('golfklubbur-bildudals.png'),
  },
  {
    id: 'medaldalsvollur',
    name: 'Meðaldalsvöllur',
    shortName: 'Þingeyri',
    location: 'Þingeyri',
    region: 'Westfjords',
    lat: 65.8703,
    lon: -23.5911,
    description: 'Golfklúbburinn Gláma. Course in the Meðaldalur valley near Þingeyri.',
    holes: 9,
    logoUrl: LOGO('glama.png'),
  },
  {
    id: 'skeljavikurvollur',
    name: 'Skeljavíkurvöllur',
    shortName: 'Hólmavík',
    location: 'Hólmavík',
    region: 'Westfjords',
    lat: 65.6855,
    lon: -21.6817,
    description: 'Golfklúbbur Hólmavíkur. Course on the shores of Steingrímsfjörður in Hólmavík.',
    holes: 9,
  },
  {
    id: 'sydridalsvollur',
    name: 'Syðridalsvöllur',
    shortName: 'Bolungarvík',
    location: 'Bolungarvík',
    region: 'Westfjords',
    lat: 66.145,
    lon: -23.2422,
    description: 'Golfklúbbur Bolungarvíkur. Course in the fishing village of Bolungarvík.',
    holes: 9,
  },
  {
    id: 'tungudalsvollur',
    name: 'Tungudalsvöllur',
    shortName: 'Ísafjörður',
    location: 'Ísafjörður',
    region: 'Westfjords',
    lat: 66.06064,
    lon: -23.19266,
    description: 'Golfklúbbur Ísafjarðar. Course in the Tungudalur valley near the Westfjords capital.',
    holes: 9,
    logoUrl: LOGO('isafjordur.jpg'),
  },
  {
    id: 'vesturbotn',
    name: 'Vesturbotn',
    shortName: 'Patreksfjörður',
    location: 'Patreksfjörður',
    region: 'Westfjords',
    lat: 65.5413,
    lon: -23.8131,
    description: 'Golfklúbbur Patreksfjarðar. Remote Westfjords course with open fjord views.',
    holes: 9,
    logoUrl: LOGO('patreksfjordur.jpg'),
  },

  // ── North Iceland ─────────────────────────────────────────────────────
  {
    id: 'arnarholtsvollur',
    name: 'Arnarholtsvöllur',
    shortName: 'Dalvík',
    location: 'Dalvík',
    region: 'North Iceland',
    lat: 65.9044,
    lon: -18.5838,
    description: 'Golfklúbburinn Hamar. Course overlooking the Eyjafjörður fjord near Dalvík.',
    holes: 9,
  },
  {
    id: 'asbyrgisvollur',
    name: 'Ásbyrgisvöllur',
    shortName: 'Ásbyrgi',
    location: 'Ásbyrgi',
    region: 'North Iceland',
    lat: 66.0285,
    lon: -16.4871,
    description: 'Golfklúbburinn Gljúfri. Remote course near the legendary horseshoe canyon of Ásbyrgi.',
    holes: 9,
  },
  {
    id: 'haagerdivollur',
    name: 'Háagerðisvöllur',
    shortName: 'Skagaströnd',
    location: 'Skagaströnd',
    region: 'North Iceland',
    lat: 65.8543,
    lon: -20.2976,
    description: 'Golfklúbbur Skagastrandar. Coastal course in the small town of Skagaströnd.',
    holes: 9,
    logoUrl: LOGO('skagastrond.jpg'),
  },
  {
    id: 'hlidarendavollur',
    name: 'Hlíðarendavöllur',
    shortName: 'Sauðárkrókur',
    location: 'Sauðárkrókur',
    region: 'North Iceland',
    lat: 65.7473,
    lon: -19.6657,
    description: 'Golfklúbbur Skagafjarðar. Course in Sauðárkrókur in the scenic Skagafjörður region.',
    holes: 9,
    logoUrl: LOGO('skagafjordur.jpg'),
  },
  {
    id: 'jadarsvollur',
    name: 'Jaðarsvöllur',
    shortName: 'Akureyri',
    location: 'Akureyri',
    region: 'North Iceland',
    lat: 65.66667,
    lon: -18.11628,
    description: 'Golfklúbbur Akureyrar. Famous 18-hole course — one of the world\'s northernmost, known for midnight sun golf.',
    holes: 18,
    logoUrl: LOGO('gba.png'),
  },
  {
    id: 'katlavollur',
    name: 'Katlavöllur',
    shortName: 'Húsavík',
    location: 'Húsavík',
    region: 'North Iceland',
    lat: 66.02897,
    lon: -17.33737,
    description: 'Golfklúbbur Húsavíkur. Course in the whale watching capital of Iceland.',
    holes: 9,
    logoUrl: LOGO('husavik.jpg'),
  },
  {
    id: 'krossdalsvollur',
    name: 'Krossdalsvöllur',
    shortName: 'Mývatn',
    location: 'Mývatn',
    region: 'North Iceland',
    lat: 65.6445,
    lon: -16.8972,
    description: 'Golfklúbbur Mývatnssveitar. Course near the lava fields and birdlife of Lake Mývatn.',
    holes: 9,
  },
  {
    id: 'lundsvollur',
    name: 'Lundsvöllur',
    shortName: 'Lundur',
    location: 'Fnjóskadalur',
    region: 'North Iceland',
    lat: 65.684,
    lon: -17.8773,
    description: 'Golfklúbburinn Lundur. Scenic course in the birch-clad Fnjóskadalur valley.',
    holes: 9,
    logoUrl: LOGO('lundur.png'),
  },
  {
    id: 'siglogolf',
    name: 'SiglóGolf',
    shortName: 'Siglufjörður',
    location: 'Siglufjörður',
    region: 'North Iceland',
    lat: 66.1302,
    lon: -18.9223,
    description: 'Golfklúbbur Siglufjarðar. Course in the former herring capital of Iceland, ringed by mountains.',
    holes: 9,
    logoUrl: LOGO('siglufjordur.png'),
  },
  {
    id: 'skeggjabrekkuvollur',
    name: 'Skeggjabrekkuvöllur',
    shortName: 'Ólafsfjörður',
    location: 'Ólafsfjörður',
    region: 'North Iceland',
    lat: 66.0674,
    lon: -18.686,
    description: 'Golfklúbbur Fjallabyggðar. Mountain-framed course in the scenic Ólafsfjörður valley.',
    holes: 9,
    logoUrl: LOGO('fjallabyggd.jpg'),
  },
  {
    id: 'vatnahverfi',
    name: 'Vatnahverfisvöllur',
    shortName: 'Blönduós',
    location: 'Blönduós',
    region: 'North Iceland',
    lat: 65.6814,
    lon: -20.234,
    description: 'Golfklúbburinn Ós. Course in Blönduós on the banks of the Blanda river.',
    holes: 9,
    logoUrl: LOGO('os.jpg'),
  },

  // ── East Iceland ──────────────────────────────────────────────────────
  {
    id: 'bygdarholt-east',
    name: 'Byggðarholtsvöllur',
    shortName: 'Byggðarholt',
    location: 'Fjarðabyggð',
    region: 'East Iceland',
    lat: 65.0815,
    lon: -14.0642,
    description: 'Golfklúbbur Byggðarholts. Course in the Fjarðabyggð fjords region of East Iceland.',
    holes: 9,
  },
  {
    id: 'ekkjufellsvollur',
    name: 'Ekkjufellsvöllur',
    shortName: 'Egilsstaðir',
    location: 'Egilsstaðir',
    region: 'East Iceland',
    lat: 65.276042,
    lon: -14.449986,
    description: 'Golfklúbbur Fljótsdalshéraðs. Course in the Fljótsdalshérað valley near Egilsstaðir.',
    holes: 9,
    logoUrl: LOGO('fljotsdalsherad.png'),
  },
  {
    id: 'graenanesvollur',
    name: 'Grænanesvöllur',
    shortName: 'Norðfjörður',
    location: 'Neskaupsstaður',
    region: 'East Iceland',
    lat: 65.1230506,
    lon: -13.77152,
    description: 'Golfklúbbur Norðfjarðar. Course in Neskaupsstaður in the East Iceland fjords.',
    holes: 9,
    logoUrl: LOGO('nordfjordur.jpg'),
  },
  {
    id: 'hagavollur',
    name: 'Hagavöllur',
    shortName: 'Seyðisfjörður',
    location: 'Seyðisfjörður',
    region: 'East Iceland',
    lat: 65.2485416,
    lon: -14.02559,
    description: 'Golfklúbbur Seyðisfjarðar. Course in the colourful historic fjord town of Seyðisfjörður.',
    holes: 9,
  },
  {
    id: 'kollur',
    name: 'Kollur',
    shortName: 'Reyðarfjörður',
    location: 'Reyðarfjörður',
    region: 'East Iceland',
    lat: 65.0336,
    lon: -14.2533,
    description: 'Golfklúbbur Fjarðabyggðar. Course in Reyðarfjörður in the East Iceland fjords.',
    holes: 9,
  },
  {
    id: 'silfurnesvollur',
    name: 'Silfurnesvöllur',
    shortName: 'Höfn',
    location: 'Höfn í Hornafirði',
    region: 'East Iceland',
    lat: 64.2638,
    lon: -15.2101,
    description: 'Golfklúbbur Hornafjarðar. Course near Höfn with views of the Vatnajökull glacier.',
    holes: 9,
    logoUrl: LOGO('hornafjordur.png'),
  },
  {
    id: 'skhalavollur',
    name: 'Skálavöllur',
    shortName: 'Vopnafjörður',
    location: 'Vopnafjörður',
    region: 'East Iceland',
    lat: 65.7428,
    lon: -14.8453,
    description: 'Golfklúbbur Vopnafjarðar. Course in the remote Vopnafjörður region of northeast Iceland.',
    holes: 9,
  },
];

export function getCourseById(id: string): Course | undefined {
  return COURSES.find((c) => c.id === id);
}

export function searchCourses(query: string): Course[] {
  const q = query
    .toLowerCase()
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, ''); // strip accents for fuzzy Icelandic match

  if (!q) return COURSES;

  return COURSES.filter((c) => {
    const fields = [
      c.name,
      c.shortName,
      c.location,
      c.region,
      c.description,
    ]
      .join(' ')
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '');

    return fields.includes(q);
  });
}

export function getDistanceKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  return Math.round(6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
}

// Curated golf course landscape photos (Unsplash) — used as fallback when no club logo is available
const FALLBACK_PHOTOS = [
  'photo-1582483955632-66bf303c11dc', // sunrise over bunker & fairway
  'photo-1614922572383-15c2ea254939', // golden hour, misty course
  'photo-1694209863469-8ba7eba63fe5', // dramatic sky, fairway
  'photo-1725835567442-7f39d9199f8c', // sunrise glow, course
  'photo-1761141987961-ed96a841fe21', // serene morning, golf green
  'photo-1707305571316-768422d5ce88', // lush fairway landscape
];

function hashCourseId(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return h;
}

/** Returns the Unsplash landscape photo for the course (never the club logo).
 *  Use this for hero backgrounds where the logo would look wrong stretched. */
export function getCoursePhotoUrl(course: Course, width = 800, height = 500): string {
  const photo = FALLBACK_PHOTOS[hashCourseId(course.id) % FALLBACK_PHOTOS.length];
  return `https://images.unsplash.com/${photo}?auto=format&fit=crop&w=${width}&h=${height}&q=80`;
}

/** Returns the club logo if available, otherwise a landscape photo.
 *  Use this for card thumbnails where the logo is the preferred visual. */
export function getCourseImageUrl(course: Course, width = 800, height = 400): string {
  if (course.logoUrl) return course.logoUrl;
  return getCoursePhotoUrl(course, width, height);
}


